#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include "Transformation.h"
#include "colour.hpp"
#include <wx/dcbuffer.h>
#include <wx/dcclient.h>
#include <wx/colordlg.h>
#include <vector>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panelRepaint( wxUpdateUIEvent& event );
		void m_option1OnRadioButton( wxCommandEvent& event );
		void m_option2OnRadioButton( wxCommandEvent& event );
		void m_option3OnRadioButton( wxCommandEvent& event );
		void m_onFunChoice( wxCommandEvent& event );
		void m_paramCtrl1OnText( wxCommandEvent& event );
		void m_paramCtrl2OnText( wxCommandEvent& event );
		void m_paramCtrl3OnText( wxCommandEvent& event );
		void m_paramCtrl4OnText( wxCommandEvent& event );
		void m_paramCtrl5OnText( wxCommandEvent& event );
		void m_paramCtrl6OnText( wxCommandEvent& event );
		void m_paramCtrl7OnText( wxCommandEvent& event );
		void m_pointsJointOnCheckBox( wxCommandEvent& event );
		void m_saveButtonOnButtonClick( wxCommandEvent& event );
		void m_rotateSlider1OnScroll( wxScrollEvent& event );
		void m_rotateSlider2OnScroll( wxScrollEvent& event );
		void m_rotateSlider3OnScroll(wxScrollEvent& event);
		void m_onAxesReset( wxCommandEvent& event );

		int funNr() const;
		void getPoints();

		double F1(double, double, double) const;
		double F2(double, double, double) const;
		double F3(double, double, double) const;

		// Wektor punktow (+ kolor)
		std::vector<std::pair<Vector, wxColour>> points;
		// Osie wspolrzednych
		std::vector<Vector> m_axes;
		std::vector<Vector> m_arrowheads;
		std::vector<Vector> m_segments;
		// Historia rotacji
		Matrix m_rotationHistory{ 1.0f };

		wxBitmap picture_bm;
		wxImage save_img;

		double m_rotX = 0.0f;
		double m_rotY = 0.0f;
		double m_rotZ = 0.0f;

		int m_phi = 0;
		int m_theta = 0;
		double m_r = 0.0f;
		double m_const = 0.0f;
		double m_epsilon = 0.0f;
		double m_delta_r = 0.0f;
		double m_r_max = 0.0f;

		int m_chartChoice = 0;

		bool m_chartChanged = false;
		bool m_funChanged = false;
		bool m_resetAxes = false;
		bool m_rChanged = false;
		bool m_phiChanged = false;
		bool m_thetaChanged = false;
		bool m_constChanged = false;
		bool m_epsilonChanged = false;
		bool m_delta_rChanged = false;
		bool m_r_maxChanged = false;

	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		Matrix GetRotationMatrix(double, double, double);
		void Repaint();
		void DrawAxes(wxBufferedDC&, Matrix, Matrix);
		void Reset();
		

};

#endif // __GUIMyFrame1__
