#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_option1OnRadioButton( wxCommandEvent& event );
		void m_option2OnRadioButton( wxCommandEvent& event );
		void m_option3OnRadioButton( wxCommandEvent& event );
		void m_paramCtrl1OnText( wxCommandEvent& event );
		void m_paramCtrl2OnText( wxCommandEvent& event );
		void m_paramCtrl3OnText( wxCommandEvent& event );
		void m_paramCtrl4OnText( wxCommandEvent& event );
		void m_paramCtrl5OnText( wxCommandEvent& event );
		void m_paramCtrl6OnText( wxCommandEvent& event );
		void m_pointsJointOnCheckBox( wxCommandEvent& event );
		void m_saveButtonOnButtonClick( wxCommandEvent& event );
		void m_rotateSlider1OnScroll( wxScrollEvent& event );
		void m_rotateSlider2OnScroll( wxScrollEvent& event );
		void m_rotateSlider3OnScroll( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members












};

#endif // __GUIMyFrame1__
