#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include "Transformation.h"
#include <wx/dcbuffer.h>
#include <wx/dcclient.h>
#include <wx/colordlg.h>
#include <vector>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_panelRepaint( wxUpdateUIEvent& event );
		void m_option1OnRadioButton( wxCommandEvent& event );
		void m_option2OnRadioButton( wxCommandEvent& event );
		void m_option3OnRadioButton( wxCommandEvent& event );
		void m_paramCtrl1OnText( wxCommandEvent& event );
		void m_paramCtrl2OnText( wxCommandEvent& event );
		void m_paramCtrl3OnText( wxCommandEvent& event );
		void m_paramCtrl4OnText( wxCommandEvent& event );
		void m_paramCtrl5OnText( wxCommandEvent& event );
		void m_paramCtrl6OnText( wxCommandEvent& event );
		void m_pointsJointOnCheckBox( wxCommandEvent& event );
		void m_saveButtonOnButtonClick( wxCommandEvent& event );
		void m_rotateSlider1OnScroll( wxScrollEvent& event );
		void m_rotateSlider2OnScroll( wxScrollEvent& event );
		void m_rotateSlider3OnScroll(wxScrollEvent& event);

		std::vector<Vector> m_axes; 

		double m_rotX = 0.0f;
		double m_rotY = 0.0f;
		double m_rotZ = 0.0f;

		double r = 0.0f;
		double phi = 0.0f;
		double teta = 0.0f;

	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Repaint();

};

#endif // __GUIMyFrame1__
